# Generated by Django 3.2.5 on 2021-09-01 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, null=True)),
                ('option_1', models.CharField(max_length=255, null=True)),
                ('option_2', models.CharField(max_length=255, null=True)),
                ('option_3', models.CharField(max_length=255, null=True)),
                ('option_4', models.CharField(max_length=255, null=True)),
                ('answer', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('percentage', models.FloatField()),
                ('time_taken', models.CharField(max_length=100, null=True)),
                ('correct', models.IntegerField()),
                ('incorrect', models.IntegerField()),
                ('total', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
